/// Display names for every territory id drawn by
/// `SMapWorld.instructionsMercator` in the countries_world_map package
/// (countries_world_map 1.3.0), keyed by the same lowercase id produced by
/// [worldMapCountryId]. Used to show a country name in the World Map bottom
/// sheet even when the tapped territory has no matching [CountrySummary].
const Map<String, String> kWorldMapCountryNames = {
  'ae': 'United Arab Emirates',
  'af': 'Afghanistan',
  'ag': 'Antigua and Barbuda',
  'ai': 'Anguilla',
  'al': 'Albania',
  'am': 'Armenia',
  'ao': 'Angola',
  'ar': 'Argentina',
  'as': 'American Samoa',
  'at': 'Austria',
  'au': 'Australia',
  'aw': 'Aruba',
  'az': 'Azerbaijan',
  'ba': 'Bosnia and Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Belgium',
  'bf': 'Burkina Faso',
  'bg': 'Bulgaria',
  'bh': 'Bahrain',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bl': 'Saint Barthelemy',
  'bm': 'Bermuda',
  'bn': 'Brunei',
  'bo': 'Bolivia',
  'bq': 'Bonaire, Sint Eustatius and Saba',
  'br': 'Brazil',
  'bs': 'Bahamas',
  'bt': 'Bhutan',
  'bw': 'Botswana',
  'by': 'Belarus',
  'bz': 'Belize',
  'ca': 'Canada',
  'cd': 'DR Congo',
  'cf': 'Central African Republic',
  'cg': 'Republic of the Congo',
  'ch': 'Switzerland',
  'ci': "Cote d'Ivoire",
  'cl': 'Chile',
  'cm': 'Cameroon',
  'cn': 'China',
  'co': 'Colombia',
  'cr': 'Costa Rica',
  'cu': 'Cuba',
  'cv': 'Cabo Verde',
  'cw': 'Curacao',
  'cy': 'Cyprus',
  'cz': 'Czechia',
  'de': 'Germany',
  'dj': 'Djibouti',
  'dk': 'Denmark',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'dz': 'Algeria',
  'ec': 'Ecuador',
  'ee': 'Estonia',
  'eg': 'Egypt',
  'eh': 'Western Sahara',
  'er': 'Eritrea',
  'es': 'Spain',
  'et': 'Ethiopia',
  'fi': 'Finland',
  'fj': 'Fiji',
  'fk': 'Falkland Islands',
  'fm': 'Micronesia',
  'fo': 'Faroe Islands',
  'fr': 'France',
  'ga': 'Gabon',
  'gb': 'United Kingdom',
  'gd': 'Grenada',
  'ge': 'Georgia',
  'gf': 'French Guiana',
  'gh': 'Ghana',
  'gl': 'Greenland',
  'gm': 'Gambia',
  'gn': 'Guinea',
  'gp': 'Guadeloupe',
  'gq': 'Equatorial Guinea',
  'gr': 'Greece',
  'gt': 'Guatemala',
  'gu': 'Guam',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'hn': 'Honduras',
  'hr': 'Croatia',
  'ht': 'Haiti',
  'hu': 'Hungary',
  'id': 'Indonesia',
  'ie': 'Ireland',
  'il': 'Israel',
  'in': 'India',
  'iq': 'Iraq',
  'ir': 'Iran',
  'is': 'Iceland',
  'it': 'Italy',
  'jm': 'Jamaica',
  'jo': 'Jordan',
  'jp': 'Japan',
  'ke': 'Kenya',
  'kg': 'Kyrgyzstan',
  'kh': 'Cambodia',
  'km': 'Comoros',
  'kn': 'Saint Kitts and Nevis',
  'kp': 'North Korea',
  'kr': 'South Korea',
  'kw': 'Kuwait',
  'ky': 'Cayman Islands',
  'kz': 'Kazakhstan',
  'la': 'Laos',
  'lb': 'Lebanon',
  'lc': 'Saint Lucia',
  'lk': 'Sri Lanka',
  'lr': 'Liberia',
  'ls': 'Lesotho',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'lv': 'Latvia',
  'ly': 'Libya',
  'ma': 'Morocco',
  'md': 'Moldova',
  'me': 'Montenegro',
  'mf': 'Saint Martin',
  'mg': 'Madagascar',
  'mh': 'Marshall Islands',
  'mk': 'North Macedonia',
  'ml': 'Mali',
  'mm': 'Myanmar',
  'mn': 'Mongolia',
  'mp': 'Northern Mariana Islands',
  'mq': 'Martinique',
  'mr': 'Mauritania',
  'ms': 'Montserrat',
  'mt': 'Malta',
  'mu': 'Mauritius',
  'mv': 'Maldives',
  'mw': 'Malawi',
  'mx': 'Mexico',
  'my': 'Malaysia',
  'mz': 'Mozambique',
  'na': 'Namibia',
  'nc': 'New Caledonia',
  'ne': 'Niger',
  'ng': 'Nigeria',
  'ni': 'Nicaragua',
  'nl': 'Netherlands',
  'no': 'Norway',
  'np': 'Nepal',
  'nr': 'Nauru',
  'nz': 'New Zealand',
  'om': 'Oman',
  'pa': 'Panama',
  'pe': 'Peru',
  'pf': 'French Polynesia',
  'pg': 'Papua New Guinea',
  'ph': 'Philippines',
  'pk': 'Pakistan',
  'pl': 'Poland',
  'pr': 'Puerto Rico',
  'ps': 'Palestine',
  'pt': 'Portugal',
  'pw': 'Palau',
  'py': 'Paraguay',
  'qa': 'Qatar',
  're': 'Reunion',
  'ro': 'Romania',
  'rs': 'Serbia',
  'ru': 'Russia',
  'rw': 'Rwanda',
  'sa': 'Saudi Arabia',
  'sb': 'Solomon Islands',
  'sc': 'Seychelles',
  'sd': 'Sudan',
  'se': 'Sweden',
  'si': 'Slovenia',
  'sj': 'Svalbard and Jan Mayen',
  'sk': 'Slovakia',
  'sl': 'Sierra Leone',
  'sn': 'Senegal',
  'so': 'Somalia',
  'sr': 'Suriname',
  'ss': 'South Sudan',
  'st': 'Sao Tome and Principe',
  'sv': 'El Salvador',
  'sx': 'Sint Maarten',
  'sy': 'Syria',
  'sz': 'Eswatini',
  'tc': 'Turks and Caicos Islands',
  'td': 'Chad',
  'tf': 'French Southern Territories',
  'tg': 'Togo',
  'th': 'Thailand',
  'tj': 'Tajikistan',
  'tl': 'Timor-Leste',
  'tm': 'Turkmenistan',
  'tn': 'Tunisia',
  'to': 'Tonga',
  'tr': 'Turkiye',
  'tt': 'Trinidad and Tobago',
  'tv': 'Tuvalu',
  'tw': 'Taiwan',
  'tz': 'Tanzania',
  'ua': 'Ukraine',
  'ug': 'Uganda',
  'us': 'United States',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  'vc': 'Saint Vincent and the Grenadines',
  've': 'Venezuela',
  'vg': 'British Virgin Islands',
  'vi': 'U.S. Virgin Islands',
  'vn': 'Vietnam',
  'vu': 'Vanuatu',
  'ws': 'Samoa',
  'xk': 'Kosovo',
  'ye': 'Yemen',
  'yt': 'Mayotte',
  'za': 'South Africa',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
};
